
# ? Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# ? 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# ? By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

result = 0
second_last, last = 0, 1

while True:
    fibonacci = last + second_last
    if fibonacci > 4_000_000:
        break
    if fibonacci % 2 == 0:
        result += fibonacci
    s_last = second_last
    second_last = last
    last = last + s_last

print(result)
